### ISSUE TITLE
计算CPU使用率的基数为啥是以物理机CPU总时间？ 而不使用容器的配额（quota）作为基数？

### ISSUE THREAD

**Issue by lianghuiyuan** [yunlzheng/docker-metrics-exporter#1]
Hello， @yunlzheng   最近在网上看k8s prometheus监控指标的资料大部分都是你的，首先向你深透的技术表达我对你的敬意 *_-。
我这几天在研究你的这个项目【docker-metrics-exporter】，遇到几个问题，想向你请教一下：
```
    private double calculateCPUPercentUnix(Long previousCPU, Long previousSystem, ContainerStats stats) {
        double cpuPercent = 0.0d;
        long cpuDelta = stats.cpuStats().cpuUsage().totalUsage() - previousCPU;
        long systemDelta = stats.cpuStats().systemCpuUsage() - previousSystem;

        if (systemDelta > 0 && cpuDelta > 0) {
            cpuPercent = getCpuUsage(cpuDelta, systemDelta) * stats.cpuStats().cpuUsage().percpuUsage().size();
        }
        return cpuPercent;
    }
```

1. 这里为啥要乘以CPU核心数【stats.cpuStats().cpuUsage().percpuUsage().size()】呢？ 
2. 计算CPU使用率的基数为啥是以物理机CPU总时间？ 而不使用容器的配额（quota）作为基数？使用物理机总资源作为k8s的指标基数，按我的理解是不准确的，使用容器的limit和require、quota会更准确一些。
3. 如果使用容器的quota作为计算使用率的基数的话，可以直接使用cAdvisor的指标，便不用自定义指标了吧，这样在工作量上也可以减少一些？

**Comment by yunlzheng** [comment]
这个之前试验的时候主要是为了和docker state的输出一致，所以这块的算法是从docker state里面搬过来的。具体你可以看一下docker的源码。

**Comment by lianghuiyuan** [comment]
嗯，谢谢你！ 这一块我已经搞清楚了。
